spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATA_SOURCE_URL:jdbc:mysql://127.0.0.1:3306/fns?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false}
    username: ${MYSQL_DATA_SOURCE_USERNAME:root}
    password: ${MYSQL_DATA_SOURCE_PASSWORD:root}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
  # 开发阶段false
    cache: false
    encoding: UTF-8
  messages:
    basename: message
  profiles:
    active: dev
#  mvc:
#    static-path-pattern: /static/**
server:
  port: 8080

config:
  dir: D:\\Downloads

# USERNAME 在系统环境变量中获取，如果获取不到默认值为 admin
username: ${USERNAME:admin}
password: ${PASSWORD:123456}

mybatis:
  table:
    auto: update
  model:
    pack: cn.aberic.fabric.dao
  database:
    type: mysql

swagger:
  print-init: true
  enabled: true
  docket:
    base-package: cn.aberic.fabric.controller

---
spring:
  profiles: test
  datasource:
    url: ${MYSQL_DATA_SOURCE_URL:jdbc:mysql://192.168.1.226:3306/fns?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false}
    username: ${MYSQL_DATA_SOURCE_USERNAME:root}
    password: ${MYSQL_DATA_SOURCE_PASSWORD:root}

config:
  dir: /home/data/config

---
spring:
  profiles: prod
  datasource:
    url: ${MYSQL_DATA_SOURCE_URL:jdbc:mysql://192.168.1.226:3306/fns?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false}
    username: ${MYSQL_DATA_SOURCE_USERNAME:root}
    password: ${MYSQL_DATA_SOURCE_PASSWORD:root}
  thymeleaf:
  # 开发阶段false
    cache: true

config:
  dir:

swagger:
  enabled: false

